name: Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    uses: openCoreEMR/github-workflows-public/.github/workflows/php-tests.yml@0.0.4
    with:
      coverage-php-version: '8.2'
